import type { Metadata } from "next";
import { Antonio } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Footer, NavBar } from "@/ui/components";

const proximaNova = localFont({
  src: "../../public/fonts/ProximaNova-Regular.otf",
  variable: "--font-paragraph",
  weight: "400",
});
const antonio = Antonio({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${proximaNova.variable} ${antonio.variable} antialiased w-screen min-h-screen flex flex-col`}
      >
        <NavBar />
        <div className="flex-1 flex flex-col w-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
